stages:
  - install
  - build
  - test
  - deploy

install_dependencies:
  stage: install
  image: node:18
  script:
    - npm install

build_project:
  stage: build
  image: node:18
  script:
    - echo "Build done"

test_project:
  stage: test
  image: node:18
  script:
    - npm test

deploy_to_ec2:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache openssh
  script:
    - echo "$SSH_PRIVATE_KEY" > key.pem
    - chmod 600 key.pem
    - ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@54.86.57.146 '
        cd express-login-app || git clone https://gitlab.com/anishasivasubramani-group/express-login-app.git && cd express-login-app &&
        git pull origin main &&
        npm install &&
        pm2 restart express-login-app || pm2 start server.js --name express-login-app
      '
